### ISSUE TITLE
Приватный baseUrl. В TypeScript изменить не получится. 

### ISSUE THREAD

**Issue by ciricc** [ivan-podgornov/rucaptcha-client#2]
Чуть по-другому сделал, не так как было в пулл реквесте, но возможность изменить endpoint появилась. Спасибо большое за идею и пулл реквест

_Originally posted by @ivan-podgornov in https://github.com/ivan-podgornov/rucaptcha-client/issues/1#issuecomment-848532571_

**Comment by ivan-podgornov** [comment]
Да, действительно. Извиняюсь, что долго не отвечал, не увидел issue. Исправил
